name: ROS2 Design
description: "Distilled design documents related to the ROS 2.0 effort"

baseurl: http://ros2.github.io/design
repo: https://github.com/ros2/design

permalink: pretty

markdown: maruku
pygments: true
