name: ROS2 Design
description: "Distilled design documents related to the ROS 2.0 effort"

baseurl: http://design.ros2.org
repo: https://github.com/ros2/design

oauth_client_id: efa6dd8eae9106381720

permalink: pretty

pygments: true

exclude:
 - CNAME
 - config.json
 - Gemfile
 - LICENSE
 - README.md
